version: 0.1

workflows:
  main:
    jobs:
    - build

jobs:
  build:
    steps:
    - clone

    - run: wget -qO- https://api.wodby.com/api/v1/get/cli?version=2.0 | sh
    - run: wodby ci init $WODBY_BUILD_ID

    - run: wodby ci build matomo
    - run: wodby ci build nginx
    - run: wodby ci release
    - run: wodby ci deploy
