name: matomo
type: service
from: php
icon: matomo
title: Matomo 5
scalable: false
update: auto
hostname: matomo
labels:
- matomo
options:
- version: '8.3'
  default: true
  
build:
  connect: true
  dockerfile: Dockerfile
  templates:
  - name: vanilla
    title: Vanilla Matomo
    repo: https://github.com/matomo-org/matomo
    tag: ^5
    pipeline: pipeline.yml

env:
- name: MATOMO_DATABASE_USERNAME
  value: '{{links.db.database.user.name}}'
- name: MATOMO_DATABASE_PASSWORD
  value: '{{links.db.database.user.password}}'
  secret: true
- name: MATOMO_DATABASE_HOST
  value: '{{links.db.database.host}}'
- name: MATOMO_DATABASE_DBNAME
  value: '{{links.db.database.db.name}}'

actions:
- name: update
  title: Run update
  args: 
  - sh 
  - -c
  - 'test ! -f config/config.ini.php || php console core:update --yes'
  type: post_deploy

