name: matomo
type: service
from: php
icon: matomo
title: Matomo 4
scalable: false
update: auto
hostname: matomo
labels:
- matomo
- matomo4
options:
- version: '8.3'
  default: true
  
build:
  connect: true
  dockerfile: Dockerfile
  templates:
  - name: vanilla
    title: Vanilla Matomo
    repo: https://github.com/matomo-org/matomo
    tag: ^4
    pipeline: pipeline.yml

actions:
- name: update
  title: Run update
  args: 
  - sh 
  - -c
  - 'test ! -f config/config.ini.php || php console core:update --yes'
  type: post_deploy

