name: matomo
type: service
icon: matomo
title: Matomo 5
scalable: false
update: auto
labels:
- matomo
- piwik

options:
- version: '5'
  default: true

containers:
- name: matomo
  image: wodby/matomo
  main: true

endpoints:
- name: fpm
  ports:
  - name: fpm
    number: 9000
    main: true
    protocol: tcp

links:
- name: db
  title: DBMS
  required: true
  env:
  - name: MATOMO_DATABASE_HOST
    value: '{{link.database.host}}'
  - name: MATOMO_DATABASE_USERNAME
    value: '{{link.database.user.name}}'
  - name: MATOMO_DATABASE_DBNAME
    value: '{{link.database.db.name}}'
  - name: MATOMO_DATABASE_PASSWORD
    value: '{{link.database.user.password}}'
    secret: true  
  selectors:
  - type: db
    labels:
    - mariadb
  - type: db
    labels:
    - mysql
- name: sendmail    
  title: Mail Transfer Agent
  required: false
  env:
  - name: MSMTP_HOST
    value: '{{link.host}}'
  - name: MSMTP_PORT
    value: '{{link.port}}'
  selectors:
  - type: service
    labels: 
    - smtpd

actions:
- name: update
  title: Run update
  args: 
  - sh 
  - -c
  - 'test ! -f config/config.ini.php || php console core:update --yes'
  type: post_deploy

helm:
  name: wodby
  source: oci://registry-1.docker.io/wodby/matomo
  chart: oci://registry-1.docker.io/wodby/matomo
  version: 0.1.0
  configurations:
  - container: matomo
    labels: podLabels
    annotations: podAnnotations
    env: envVars
    resources: resources
    volumes: extraVolumes
    mounts: extraVolumeMounts
