name: matomo
type: service
from: php
icon: matomo
title: Matomo 4
hostname: matomo
labels:
- matomo
- matomo4
options:
- version: 4
  default: true
containers:
- name: matomo
  image: wodby/matomo
  main: true
